-- Live seed from DVC Spring/Summer/Fall 2026 schedule
-- Run this AFTER schema.sql
-- Safe to re-run: truncates and re-inserts

TRUNCATE TABLE ai_summaries, reviews, professors RESTART IDENTITY CASCADE;

-- Add courses column if it doesn't exist
ALTER TABLE professors ADD COLUMN IF NOT EXISTS courses text DEFAULT '';

INSERT INTO professors (name, department, courses) VALUES
('Claudia Abadia', 'Mathematics', 'MATH-114, MATH-193'),
('Santino Aguilar', 'Computer Information Systems', 'CIS-116, CIS-117'),
('Rachid Allata', 'Music', 'MUSIC-150, MUSIC-151, MUSIC-250'),
('Ervin Anderson', 'Kinesiology', 'KNICA-098, KNICA-199, KNICA-202A, KNICA-202B'),
('Lisa Ang', 'English', 'ENGL-224'),
('Mitchell Anthony', 'History', 'HIST-120, HIST-124'),
('James Arthur', 'Mathematics', 'MATH-193'),
('Sherry Ayres', 'Kinesiology', 'KNACT-132'),
('Glen Barker', 'Kinesiology', 'AKINES-234'),
('Derek Baure', 'Kinesiology', 'KNACT-210, KNACT-224'),
('Carlos Bazua', 'Anthropology', 'ANTHR-130'),
('Petrice Beattie', 'Kinesiology', 'KNICA-199, KNICA-203A, KNICA-203B'),
('Ellen Beaulieu', 'Humanities', 'GINTD-080NC, HINTD-081NC'),
('Meera Bhadra', 'Psychology', 'PSYC-122'),
('Milissa Bradley', 'Kinesiology', 'KINES-110'),
('Monica Brennan', 'Computer Information Systems', 'CIS-100, CIS-108, CIS-133, CIS-140'),
('Dick Buckingham', 'Engineering Technology', 'DENGTC-160, EET-140'),
('Ryan Buckley', 'Business Administration', 'BUSMK-260'),
('Susan Burgess', 'English', 'ENGL-C1000, ENGL-C1001, ENGL-C1003'),
('Oscar Cabezas', 'Culinary Arts', 'HOSP-155, HOSP-266'),
('Elizabeth Cabiles', 'Business Administration', 'BUS-250, CIS-116'),
('Ana Carbonell', 'English', 'ENGL-225'),
('Jamylle Carter', 'Mathematics', 'MATH-121, STAT-C1000'),
('Doug Cembellin', 'Film & Digital Media', 'FTVE-282'),
('Jason Chan', 'Business Administration', 'BUS-104'),
('Christine Chang', 'Culinary Arts', 'HOSP-155, HOSP-186'),
('Thomas Chatagnier', 'Engineering Technology', 'EET-100'),
('Angela Chen', 'Dental Hygiene', 'BDENHY-129'),
('Nadine Chin', 'Business Administration', 'BUS-104, BUSAC-188'),
('Edward Collins', 'Geography', 'GEOG-120'),
('James Collins', 'Kinesiology', 'KNICA-206'),
('John Corbally', 'History', 'HIST-122, HIST-140, HIST-141, HIST-142, HIST-180, HIST-181, INTD-100'),
('Manuel Covarrubias', 'Engineering Technology', 'EET-107'),
('Sumanjari Das', 'Biological Sciences', 'BIOL-146, BIOSC-119'),
('Maria Dawson', 'Counseling', 'COUNS-100'),
('Joann Denning', 'Film & Digital Media', 'ARTDM-214'),
('Corey Dolley', 'Kinesiology', 'KNICA-224'),
('Raine Dougan', 'Counseling', 'COUNS-125'),
('Alexandra Dutton', 'Early Childhood Education', 'ECE-244'),
('Lauren Eastland', 'Anthropology', 'ANTHR-120'),
('Martina Ebesugawa', 'Early Childhood Education', 'ECE-124'),
('Rachel Egoian', 'English', 'ENGL-123'),
('Marci Ekberg', 'Biological Sciences', 'BIOL-130, BIOL-171, BIOSC-171'),
('Caitlin Erickson', 'Communication Studies', 'COMM-C1000'),
('Steven Faghih', 'Computer Information Systems', 'CIS-115, CIS-118'),
('Matthew Fein', 'Biological Sciences', 'BIOL-139, BIOL-146'),
('Megan Ferrara', 'Humanities', 'HUMAN-105'),
('John Fogli', 'Business Administration', 'BUS-109, BUSMK-261'),
('David Foulds', 'Film & Digital Media', 'FTVE-140'),
('Sandra Gardiner', 'English', 'IESL-087, PESL-087NC'),
('Heather Gilardi', 'Nutrition', 'NUTRI-130'),
('Richard Glaves', 'Biological Sciences', 'BIOL-139, BIOL-140, PH-105'),
('Toby Gloekler', 'Administration of Justice', 'ADJUS-206'),
('Anthony Gonzales', 'English', 'ENGL-140B'),
('Marisa Greenberg', 'Counseling', 'WRKX-170'),
('George Hanna', 'Counseling', 'CARER-110, COUNS-095NC, COUNS-120'),
('Megan Hansen', 'Dental Hygiene', 'DENGL-140C'),
('Pamela Harrison', 'Administration of Justice', 'ADJUS-124, ADJUS-230'),
('Nick Hedayat', 'Biological Sciences', 'BIOL-139, BIOSC-140'),
('Richard Herman', 'English', 'ENGTC-165'),
('Derene Hinchliff', 'Business Administration', 'BUSEN-001NC, BUSEN-002NC'),
('Shaeehea Hollis', 'Counseling', 'CARER-110'),
('Russell Holt', 'Engineering Technology', 'EET-155'),
('Lynn Huang', 'English', 'ENGL-123, ENGL-C1000'),
('Jessika Hughes', 'Interdisciplinary Studies', 'INTD-040'),
('Julie Hui', 'Anthropology', 'ANTHR-140'),
('Kimberlee Hunter', 'Communication Studies', 'COMM-C1000'),
('Lance Hurtado', 'Administration of Justice', 'ADJUS-295, ADJUS-296'),
('Loc Huynh', 'Business Administration', 'BUS-109, BUSAC-186, CIS-107, CIS-116, CIS-120, CIS-130, CIS-160'),
('Monique Iles', 'English', 'ENGL-140A'),
('Rupinder Jagpal', 'Computer Science', 'COMSC-101, LCOMSC-010NC'),
('Christie Jamshidnejad', 'Counseling', 'CARER-110, CARER-120, COUNS-095NC'),
('Liana Johnson', 'Art', 'IDSGN-120'),
('Howard Jordan', 'Administration of Justice', 'ADJUS-030NC, ADJUS-120'),
('Bruce Jower', 'Administration of Justice', 'ADJUS-100, ADJUS-121, ADJUS-125'),
('Shawn Kammerer', 'Construction Technology', 'CONST-105'),
('Tony Kashani', 'Film & Digital Media', 'FTVE-210'),
('Clarissa Katko', 'English', 'ENGL-C1000, ENGL-C1000E'),
('Anim Khalid', 'Computer Information Systems', 'CIS-116, CIS-118'),
('Donna Kimmel-Lake', 'Administration of Justice', 'ADJUS-203, ADJUS-206'),
('Arthur King', 'Art', 'ARTDM-102'),
('Caitlin King', 'Biological Sciences', 'BIOL-140'),
('Alexis Kline', 'Biological Sciences', 'BIOL-139'),
('Devaney Knight', 'Psychology', 'PSYC-200'),
('Martha Laham', 'Business Administration', 'BUSMK-258, BUSMK-262'),
('Xinyi Lai', 'Computer Science', 'COMSC-140'),
('Krishna Lamichhane', 'Physics', 'PHYS-121'),
('Gwen Lang', 'Dental Hygiene', 'DENHY-127'),
('Lindsey Lang', 'Mathematics', 'MATH-191'),
('Samantha Lasater', 'Biological Sciences', 'BIOSC-116'),
('Sheila Lau', 'Counseling', 'COUNS-130NC'),
('Kyung-Min Lee', 'Physics', 'PHYS-124'),
('Paula Leon-Bravo', 'Mathematics', 'MATH-192'),
('Christine Leptien-Parks', 'Engineering', 'CONST-116, ENGIN-140'),
('Anna Levin', 'Biological Sciences', 'BBIOL-131, BIOL-170, BIOL-C1000'),
('Noelle Lopez', 'Psychology', 'PSYC-C1000'),
('Dennis Luquet', 'Kinesiology', 'KNICA-199, KNICA-200'),
('Tarra Lyons', 'Art', 'ART-101'),
('Rob Manheimer', 'English', 'ENGTC-110'),
('Isabella Mariano', 'History', 'GHIST-129, HIST-121, HIST-C1002'),
('Annie Martin', 'Kinesiology', 'AKINES-234'),
('Reed Martin', 'Drama', 'DRAMA-202, DRAMA-270'),
('Joel Matthews', 'Engineering Technology', 'EET-100'),
('Christina McDade', 'Interdisciplinary Studies', 'INTD-100'),
('Kristen McLeran', 'Administration of Justice', 'ADJUS-120, ADJUS-121'),
('Andrea Medina', 'Film & Digital Media', 'FTVE-210, FTVE-282'),
('Patrick Moe', 'Communication Studies', 'COMM-C1000'),
('Adhitya Mohan', 'Mathematics', 'MATH-294'),
('Santina Mongold', 'Biological Sciences', 'BIOL-C1001, BIOSC-116'),
('Matthew Morrissey', 'Administration of Justice', 'ADJUS-120, ADJUS-121, ADJUS-122, ADJUS-130, ADJUS-221, ADJUS-222'),
('Yasser Moten', 'Communication Studies', 'COMM-121, COMM-C1000'),
('Cailin Mullins', 'Kinesiology', 'KNICA-210'),
('Kristin Munk', 'Dental Assisting', 'DENTL-160, DENTL-182'),
('Amber Naeem', 'History', 'HIST-C1001'),
('Mauricio Najarro', 'Accounting', 'BUSAC-186, BUSAC-187'),
('Devin Nonies', 'Kinesiology', 'KNICA-199'),
('Sean Nowicki', 'Art History', 'ARTHS-195, ARTHS-196'),
('Shola Ogunlana', 'Administration of Justice', 'ADJUS-040NC'),
('Frank Ortega', 'Sociology', 'SOCIO-135'),
('Douglas Pena', 'Computer Information Systems', 'CIS-180'),
('Bret Peppo', 'Music', 'MUSIC-135, MUSIC-256'),
('Steven Peterson', 'Counseling', 'ADS-151'),
('Douglas Phenix', 'Counseling', 'COUNS-095NC'),
('Shelly Pierson', 'Kinesiology', 'KINES-210, KNICA-199, KNICA-204, KNICA-205'),
('Jacqueline Ponciano-Babb', 'Kinesiology', 'KNICA-223'),
('Aaron Prater', 'Culinary Arts', 'HOSP-161'),
('Trisha Quan', 'Kinesiology', 'KNICA-216, KNICA-217, KNICA-225'),
('Christopher Rasmussen', 'Humanities', 'IHUMAN-110'),
('Brandon Reyes', 'Biological Sciences', 'BIOL-162, ENVSC-100'),
('Francis Reyes', 'Computer Network Technology', 'CNT-101, CNT-102'),
('Joan Riley', 'Anthropology', 'ANTHR-130'),
('Sara Ringo', 'Counseling', 'COUNS-120, INTD-040'),
('Julie Rodriguez', 'Dental Assisting', 'DENTL-120NC, DENTL-160, DENTL-182'),
('Shirley Rubin', 'Anthropology', 'ANTHR-130'),
('Andrew Rush', 'Biological Sciences', 'BIOL-C1000'),
('Carmen Santana', 'Administration of Justice', 'ADJUS-100, ADJUS-120, ADJUS-121'),
('Michael Scalzi', 'Philosophy', 'PHILO-120'),
('Bridgitte Schaffer', 'History', 'HIST-124, HIST-C1002'),
('Noah Schillo', 'Geography', 'GEOG-120'),
('Roxann Schmidt', 'English', 'ENGL-C1000'),
('Glenn Scott', 'Mathematics', 'MATH-192'),
('Matthew Self', 'Physics', 'PHYS-129'),
('Charles Shackett', 'English', 'ENGL-176'),
('Bashir Shah', 'Business Administration', 'BUS-294'),
('Amber Shields', 'Film & Digital Media', 'FTVE-205'),
('Colleen Shipp', 'Dental Assisting', 'DENTL-120NC'),
('Binita Sinha', 'Geography', 'GEOG-120, GEOG-126'),
('Laura Siragusa', 'Counseling', 'CARER-101'),
('Patricia Slechta', 'English', 'ENGTC-175'),
('Donna Smith', 'Journalism', 'JRNAL-110'),
('Jeffrey Smith', 'Engineering', 'EET-107, ENGTC-180, IDSGN-105'),
('Robin Smith-Gilbert', 'Computer Information Systems', 'CIS-181'),
('Anna Sohi', 'Mathematics', 'MATH-124'),
('Paula Stanfield', 'Counseling', 'COUNS-120NC'),
('Tonette Steeb', 'Dental Hygiene', 'DENHY-101NC'),
('Kathryn Stine', 'Library', 'LT-107'),
('Marlene Storz', 'Dental Hygiene', 'DENHY-101NC, DENHY-127'),
('Joanne Strickland', 'Computer Science', 'COMSC-110'),
('Brendan Sullivan', 'Communication Studies', 'COMM-125, COMM-128'),
('Beverly Symmank', 'Chemistry', 'CHEM-108'),
('Beaux Tagaloa', 'Kinesiology', 'KNICA-199'),
('Shahin Tajbakhsh', 'Computer Network Technology', 'ICNT-010NC, JCNT-020NC'),
('Mario Tejada', 'Computer Information Systems', 'CIS-101, CIS-105'),
('Granada Tezeno', 'Kinesiology', 'KNICA-199, KNICA-220, KNICA-221'),
('Robert Trujillo', 'Administration of Justice', 'ADJUS-139'),
('Peikun Tsai', 'Computer Science', 'COMSC-210'),
('Kimberly Valmore', 'Dance', 'DANCE-212, DANCE-213, DANCE-214, DANCE-216'),
('Christopher Vettel', 'Music', 'MUSIC-110, MUSIC-117'),
('Ryan Wallace', 'Communication Studies', 'COMM-128'),
('Carolyn Warren', 'Counseling', 'CARER-110, COUNS-095, COUNS-095NC'),
('Andrew Welch', 'Kinesiology', 'KNACT-174A, KNACT-174B'),
('Justin Wembes', 'Counseling', 'COUNS-095NC'),
('Meghan Westlander', 'Physics', 'PHYS-124'),
('Nicole White', 'Art', 'ARTDM-136, ARTHS-196, INTD-100'),
('James Wilson', 'English', 'ENGL-C1001'),
('Solomon Wilson', 'Counseling', 'COUNS-096'),
('Gaby Wolodarski', 'Art', 'ART-105, ART-106, ART-120, ART-121, ART-126, ART-127, ART-129'),
('Bill Wolter', 'Music', 'MUSIC-256'),
('Scott Wood', 'Kinesiology', 'KNICA-199, KNICA-215'),
('Angeline Yambao', 'Dental Hygiene', 'BDENHY-129'),
('Kenneth Zeglin', 'Business Administration', 'BUS-109'),
('Katie Zeigler', 'English', 'ENGL-222'),
('Joe Zermeno', 'Biological Sciences', 'BIOL-139'),
('David Zimring', 'History', 'HIST-124');
